### PR TITLE
[RSPEC MODEL] Room model rspec

### PR DESCRIPTION
**Pull request by huytn-1183**
## Related Tickets
- [#43129](https://edu-redmine.sun-asterisk.vn/issues/43129)
- [#43130](https://edu-redmine.sun-asterisk.vn/issues/43130)
- [#43131](https://edu-redmine.sun-asterisk.vn/issues/43131)

## WHAT (optional)
- search with nil keyword
- query empty attributes
- query invalid pagination

## HOW
- Rspec model room

## Evidence (Screenshot or Video)
image

### CODE REVIEW

**Comment by huytn-1183** [comment]
ready

**Comment by vanvtt-0952** [comment]
commented
Conflict code

**Comment by huytn-1183** [comment]
ready

**Comment by vanvtt-0952** [comment]
commented
conflict code

**Comment by huytn-1183** [comment]
rady

**Comment by huytn-1183** [comment]
ready

**Pull request merged**
